name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sub-service

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install uv
      run: |
        pip install uv
    - name: Install dependencies
      run: |
        uv sync --locked
    - name: Run tests
      run: |
        uv run pytest
    - name: Run ruff check
      run: |
        uv run ruff check .
    - name: Run ruff format
      run: |
        uv run ruff format . --check
